-- Bolivar Peninsula & Galveston area facts seed
-- Run after creating the facts table

INSERT INTO facts (area, title, short_fact, long_fact, category) VALUES
  ('Bolivar', 'Named for Simón Bolívar', 'The peninsula is named for Simón Bolívar, the South American liberator.', 'Bolivar Peninsula takes its name from Simón Bolívar, the leader of independence movements in South America.', 'history'),
  ('Bolivar', 'Narrow barrier landform', 'Bolivar Peninsula is a narrow strip of eroding land along the Texas Gulf Coast.', 'Bolivar Peninsula is a narrow, eroding barrier landform stretching along the Texas Gulf Coast.', 'geography'),
  ('Bolivar', 'About 27 miles long', 'The peninsula stretches twenty-seven miles along the Texas Gulf Coast.', 'Bolivar Peninsula extends about 27 miles along the Texas Gulf Coast.', 'geography'),
  ('Bolivar', 'Forms eastern Galveston County', 'It forms the eastern part of Galveston County.', 'Bolivar Peninsula makes up the eastern part of Galveston County.', 'geography'),
  ('Bolivar', 'Separates bay from gulf', 'It separates the eastern part of Galveston Bay from the Gulf of Mexico.', 'Bolivar Peninsula lies between Galveston Bay and the Gulf of Mexico.', 'geography'),
  ('Bolivar', 'Short ferry ride from Galveston', 'The peninsula is a short ferry ride from Galveston, Texas.', 'Travel between Galveston and Bolivar is commonly done by ferry.', 'transportation'),
  ('Bolivar', 'Ferry is toll-free', 'The Galveston-Port Bolivar Ferry is a toll-free service operated by TxDOT.', 'Riding the Galveston-Port Bolivar Ferry does not require a toll.', 'transportation'),
  ('Bolivar', 'Ferry runs 24 hours', 'The ferry operates 24 hours a day.', 'Ferry service between Galveston and Bolivar runs around the clock.', 'transportation'),
  ('Bolivar', 'Ferry began in 1930', 'Ferry service began on April 12, 1930.', 'The Galveston-Port Bolivar Ferry started operating on April 12, 1930.', 'history'),
  ('Bolivar', 'Port Bolivar ferry terminal', 'The Port Bolivar ferry terminal is at 123 SH 87, Port Bolivar, TX.', 'Port Bolivar is one of the ferry endpoints on SH 87.', 'transportation'),
  ('Bolivar', 'Galveston terminal on Ferry Road', 'The Galveston terminal is at 1000 Ferry Road, Galveston, TX.', 'Galveston''s ferry terminal sits on Ferry Road.', 'transportation'),
  ('Bolivar', 'Ferry may stop in severe weather', 'Service may be reduced or stopped during severe weather for safety.', 'The ferry can be limited or suspended when weather is dangerous.', 'transportation'),
  ('Bolivar', 'Includes Port Bolivar community', 'The peninsula includes the community of Port Bolivar.', 'Port Bolivar is one of the named communities on Bolivar Peninsula.', 'communities'),
  ('Bolivar', 'Includes Crystal Beach', 'The peninsula includes Crystal Beach.', 'Crystal Beach is a major community on Bolivar Peninsula.', 'communities'),
  ('Bolivar', 'Includes Caplen', 'The peninsula includes Caplen.', 'Caplen is part of the Bolivar Peninsula community cluster.', 'communities'),
  ('Bolivar', 'Includes Gilchrist', 'The peninsula includes Gilchrist.', 'Gilchrist is a community on Bolivar Peninsula.', 'communities'),
  ('Bolivar', 'Includes High Island', 'The peninsula includes High Island.', 'High Island is part of the broader Bolivar Peninsula area.', 'communities'),
  ('Bolivar', 'Popular for fishing', 'It is popular for fishing.', 'Fishing is one of the common recreation activities on Bolivar Peninsula.', 'recreation'),
  ('Bolivar', 'Popular for boating', 'It is popular for boating.', 'Boating is a common use of the waters around Bolivar Peninsula.', 'recreation'),
  ('Bolivar', 'Popular for bird watching', 'It is popular for bird watching.', 'Bird watching is a well-known activity on Bolivar Peninsula.', 'recreation'),
  ('Bolivar', 'Popular for beach days', 'It is popular for spending a day on the beach.', 'Visitors often go to Bolivar Peninsula for beach time.', 'recreation'),
  ('Bolivar', 'Bolivar Beach Pavilion', 'Bolivar Beach Pavilion offers beach access, parking, restrooms, and rinse-off showers.', 'Bolivar Beach Pavilion is a public beach facility with visitor amenities.', 'amenities'),
  ('Bolivar', 'Fort Travis in Port Bolivar', 'Fort Travis Park is at 800 Anderson Ave., Port Bolivar.', 'Fort Travis Park is located in Port Bolivar on Bolivar Peninsula.', 'history'),
  ('Bolivar', 'Fort Travis is historic', 'Fort Travis Park is listed as a historic site.', 'Fort Travis Park is recognized as a historic location.', 'history'),
  ('Bolivar', 'Point Bolivar Lighthouse guided ships', 'The Point Bolivar Lighthouse guided boat traffic through Bolivar Roads.', 'The lighthouse helped guide vessels through the pass between bay and gulf.', 'history'),
  ('Bolivar', 'Lighthouse operated 1873 to 1933', 'It operated from 1873 to 1933.', 'The Point Bolivar Lighthouse was in service for six decades.', 'history'),
  ('Bolivar', 'Bolivar Roads is a narrow pass', 'Bolivar Roads is a 1.5-mile-wide pass between the Gulf and the Bay.', 'Bolivar Roads is the narrow maritime passage near Bolivar Peninsula.', 'geography'),
  ('Bolivar', 'High Island on a salt dome', 'High Island sits atop a salt dome about 45 feet above sea level.', 'High Island rises unusually high because it rests on a salt dome.', 'geology'),
  ('Bolivar', 'High Island stays dry in floods', 'During severe flooding it is the only dry land seen for miles.', 'High Island becomes a rare dry spot during big coastal floods.', 'geology'),
  ('Bolivar', 'High Island settled in 1834', 'Martin Dunman settled at High Island in 1834.', 'High Island''s recorded settlement dates to 1834.', 'history'),
  ('Bolivar', 'Rail access by 1886', 'The Gulf and Interstate Railroad built a railroad to Beaumont along Bolivar Peninsula in 1886.', 'Rail development reached High Island and the peninsula in the late 1800s.', 'history'),
  ('Bolivar', 'High Island had mineral springs', 'For a time the community was known for its mineral springs.', 'High Island once had a reputation for mineral springs.', 'history'),
  ('Bolivar', 'High Island oil boom', 'Oil was discovered in 1916 and a major oil boom followed in the 1930s and 1940s.', 'High Island became part of a regional oil boom after discovery in 1916.', 'history'),
  ('Bolivar', 'Seaview Hotel sheltered residents', 'The Seaview Hotel served as shelter during hurricanes in 1900 and 1915.', 'A hotel in the area provided refuge during major hurricanes.', 'history'),
  ('Bolivar', 'Part of Galveston County', 'Bolivar Peninsula is in Galveston County, Texas.', 'Bolivar Peninsula belongs to Galveston County.', 'location'),
  ('Bolivar', 'Gulf Coast region', 'The Texas Gulf Coast includes Galveston and the surrounding coastal communities.', 'Bolivar is part of the broader Texas Gulf Coast environment.', 'location'),
  ('Bolivar', 'About 3,000 residents in 2023', 'In 2023 Bolivar Peninsula had a population of about 3,000.', 'Bolivar Peninsula is a small but growing coastal community.', 'demographics'),
  ('Bolivar', 'Median age 62.6', 'In 2023 the median age was 62.6.', 'Bolivar Peninsula has an older population profile.', 'demographics'),
  ('Bolivar', 'Median household income $71,970', 'In 2023 the median household income was $71,970.', 'Bolivar Peninsula''s median household income was about $71,970 in 2023.', 'demographics'),
  ('Bolivar', 'Population grew 14.1 percent', 'Population grew from 2,626 to 2,995 between 2022 and 2023.', 'Bolivar Peninsula''s population increased sharply year over year.', 'demographics'),
  ('Bolivar', 'Homeownership 91.7 percent', 'Homeownership rate was 91.7 percent in 2023.', 'Most Bolivar Peninsula households own their homes.', 'housing'),
  ('Bolivar', 'Median property value $316,400', 'Median property value was $316,400 in 2023.', 'Bolivar Peninsula''s housing values were around $316,400 in 2023.', 'housing'),
  ('Bolivar', 'Commute averages 45 minutes', 'Average commute time was 45.3 minutes.', 'Commuters on Bolivar Peninsula spend a long time traveling to work.', 'transportation'),
  ('Bolivar', 'Residents mostly drive alone', 'Most people drove alone to work.', 'Driving alone is the dominant commute mode on Bolivar Peninsula.', 'transportation'),
  ('Bolivar', 'About 2 cars per household', 'Average car ownership was 2 cars per household.', 'Households on Bolivar Peninsula typically have about two cars.', 'transportation'),
  ('Bolivar', 'Mostly English-speaking', 'None of the households reported a non-English language as the primary shared language at home.', 'English is the dominant home language on Bolivar Peninsula.', 'demographics'),
  ('Bolivar', 'Majority White non-Hispanic', 'White non-Hispanic residents were the largest ethnic group.', 'Bolivar Peninsula''s population is majority White non-Hispanic.', 'demographics'),
  ('Bolivar', '93.5 percent U.S. citizens', '93.5 percent of residents were U.S. citizens.', 'Most Bolivar Peninsula residents are U.S. citizens.', 'demographics'),
  ('Bolivar', 'Long-time vacation-home area', 'The peninsula had hundreds of vacation-home owners and weekend visitors in the 1990s.', 'Bolivar Peninsula has long been a second-home and weekend destination.', 'tourism'),
  ('Bolivar', 'Eroding barrier landform', 'It is described as an eroding landform.', 'Coastal erosion is part of Bolivar Peninsula''s physical reality.', 'geography'),
  ('Bolivar', 'Southeast Texas coast', 'It stretches along the Texas Gulf Coast in eastern Galveston County.', 'Bolivar Peninsula sits on the southeast Texas shoreline.', 'geography'),
  ('Bolivar', 'Center at 29°26 N, 94°41 W', 'The center of the peninsula is at 29°26 N, 94°41 W.', 'The peninsula''s center has published geographic coordinates.', 'geography'),
  ('Bolivar', 'Beach access at the Pavilion', 'Bolivar Beach Pavilion offers beach access and parking.', 'Public access infrastructure supports beach visits on Bolivar Peninsula.', 'amenities'),
  ('Bolivar', 'National Register historic sites', 'Fort Travis and Point Bolivar Lighthouse are listed on the National Register of Historic Places in Texas.', 'Bolivar Peninsula contains nationally recognized historic places.', 'history'),
  ('Bolivar', 'Strong recreation identity', 'Outdoor recreation is a major theme for the peninsula.', 'Bolivar is known for outdoor leisure rather than dense urban development.', 'recreation'),
  ('Bolivar', 'Ferry is the main access point', 'The ferry is the main connection between Galveston Island and the peninsula.', 'Access to Bolivar often depends on the ferry crossing.', 'transportation'),
  ('Bolivar', 'Part of county parks system', 'The county parks page identifies the peninsula as a park/recreation area.', 'County government treats Bolivar Peninsula as a recreation destination.', 'government'),
  ('Bolivar', 'Crystal Beach has a pavilion', 'Crystal Beach is within Bolivar and has a dedicated beach pavilion.', 'Crystal Beach is a central beach community on Bolivar Peninsula.', 'communities'),
  ('Bolivar', 'Lighthouse guided maritime traffic', 'The lighthouse guided boats through a key maritime pass.', 'Bolivar''s lighthouse story is tied to navigation and shipping.', 'history'),
  ('Bolivar', 'Hurricane shelter history', 'The Seaview Hotel sheltered peninsula residents during hurricanes.', 'Storm response has shaped Bolivar Peninsula''s history.', 'history'),
  ('Bolivar', 'Rail line linked to Beaumont', 'The railroad along Bolivar Peninsula linked toward Beaumont.', 'Rail development tied Bolivar to larger regional routes.', 'history'),
  ('Bolivar', 'Beach-centered tourism', 'The area is known for beach time, fishing, boating and birding.', 'Tourism on Bolivar Peninsula centers on the coast and wildlife.', 'tourism'),
  ('Bolivar', 'Part of a barrier-island system', 'Bolivar is described as a barrier island/barrier formation.', 'Bolivar Peninsula functions like a barrier island on the Gulf.', 'geography'),
  ('Bolivar', 'Near Galveston Bay shipping lanes', 'Bolivar Roads connects the bay and gulf for vessels.', 'The peninsula sits next to an important maritime corridor.', 'navigation');
